spring.application.name=bovine-link-api

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/bovine_link
spring.datasource.username=postgres
spring.datasource.password=chipi1213
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Locale El Salvador
spring.jackson.locale=es_SV
spring.jackson.time-zone=America/El_Salvador

# JWT
jwt.secret=bovineLink2026ClaveSecretaSuperLargaParaJWT123456
jwt.expiration=86400000

server.port=8080
