-- ============================================================
-- Bovine Link API - Esquema inicial (segun diagrama E-R)
-- Motor: PostgreSQL
-- ============================================================

-- ---------- roles ----------
CREATE TABLE roles (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT uk_roles_name UNIQUE (name)
);

-- ---------- users ----------
CREATE TABLE users (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(255) NOT NULL,
    email          VARCHAR(255) NOT NULL,
    telefono       VARCHAR(20),
    password       VARCHAR(250) NOT NULL,
    remember_token VARCHAR(100),
    rol_id         BIGINT       NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT fk_users_rol FOREIGN KEY (rol_id) REFERENCES roles (id)
);

CREATE INDEX idx_users_rol ON users (rol_id);

-- ---------- razas ----------
CREATE TABLE razas (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre    VARCHAR(255) NOT NULL,
    categoria VARCHAR(30)  NOT NULL,
    CONSTRAINT ck_razas_categoria CHECK (categoria IN ('LECHE', 'CARNE', 'DOBLE_PROPOSITO'))
);

-- ---------- publicaciones ----------
CREATE TABLE publicaciones (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo_venta VARCHAR(255)   NOT NULL,
    descripcion  TEXT           NOT NULL,
    ubicacion    VARCHAR(255)   NOT NULL,
    precio       NUMERIC(12, 2) NOT NULL,
    estado       VARCHAR(20)    NOT NULL DEFAULT 'EN_VENTA',
    vendido_en   TIMESTAMP,
    created_at   TIMESTAMP,
    updated_at   TIMESTAMP,
    user_id      BIGINT         NOT NULL,
    raza_id      BIGINT         NOT NULL,
    CONSTRAINT fk_publicaciones_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_publicaciones_raza FOREIGN KEY (raza_id) REFERENCES razas (id),
    CONSTRAINT ck_publicaciones_estado CHECK (estado IN ('EN_VENTA', 'VENDIDO'))
);

CREATE INDEX idx_publicaciones_user   ON publicaciones (user_id);
CREATE INDEX idx_publicaciones_raza   ON publicaciones (raza_id);
CREATE INDEX idx_publicaciones_estado ON publicaciones (estado);

-- ---------- imagenes ----------
CREATE TABLE imagenes (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url            TEXT    NOT NULL,
    foto_portada   BOOLEAN NOT NULL DEFAULT FALSE,
    publicacion_id BIGINT  NOT NULL,
    CONSTRAINT fk_imagenes_publicacion FOREIGN KEY (publicacion_id)
        REFERENCES publicaciones (id) ON DELETE CASCADE
);

CREATE INDEX idx_imagenes_publicacion ON imagenes (publicacion_id);
