-- ============================================================
-- Bovine Link API - Esquema inicial
-- Motor: PostgreSQL 18
-- Generado a partir de las entidades JPA (com.bovinelink.bovinelinkapi.entity)
-- ============================================================

-- ---------- usuarios ----------
CREATE TABLE usuarios (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre         VARCHAR(100) NOT NULL,
    correo         VARCHAR(150) NOT NULL,
    telefono       VARCHAR(20),
    password       VARCHAR(255) NOT NULL,
    rol            VARCHAR(255) NOT NULL DEFAULT 'USUARIO',
    fecha_registro TIMESTAMP,
    CONSTRAINT uk_usuarios_correo UNIQUE (correo),
    CONSTRAINT ck_usuarios_rol CHECK (rol IN ('USUARIO', 'ADMIN'))
);

-- ---------- razas ----------
CREATE TABLE razas (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre    VARCHAR(100) NOT NULL,
    categoria VARCHAR(30)  NOT NULL,
    CONSTRAINT ck_razas_categoria CHECK (categoria IN ('LECHE', 'CARNE', 'DOBLE_PROPOSITO'))
);

-- ---------- publicaciones ----------
CREATE TABLE publicaciones (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo             VARCHAR(150)   NOT NULL,
    descripcion        TEXT           NOT NULL,
    precio             NUMERIC(12, 2) NOT NULL,
    ubicacion          VARCHAR(150)   NOT NULL,
    estado             VARCHAR(20)    NOT NULL DEFAULT 'EN_VENTA',
    usuario_id         BIGINT         NOT NULL,
    raza_id            BIGINT         NOT NULL,
    fecha_publicacion  TIMESTAMP,
    CONSTRAINT fk_publicaciones_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id),
    CONSTRAINT fk_publicaciones_raza    FOREIGN KEY (raza_id)    REFERENCES razas (id),
    CONSTRAINT ck_publicaciones_estado  CHECK (estado IN ('EN_VENTA', 'VENDIDO'))
);

CREATE INDEX idx_publicaciones_usuario ON publicaciones (usuario_id);
CREATE INDEX idx_publicaciones_raza    ON publicaciones (raza_id);
CREATE INDEX idx_publicaciones_estado  ON publicaciones (estado);

-- ---------- fotos_publicacion ----------
CREATE TABLE fotos_publicacion (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url            VARCHAR(255) NOT NULL,
    publicacion_id BIGINT       NOT NULL,
    CONSTRAINT fk_fotos_publicacion FOREIGN KEY (publicacion_id)
        REFERENCES publicaciones (id) ON DELETE CASCADE
);

CREATE INDEX idx_fotos_publicacion ON fotos_publicacion (publicacion_id);
